listen_addr = "0.0.0.0:8765"
issuer_url = "https://oauth.example.org"
introspect_url = "https://oauth.example.org/token/introspect"
client_id = "client id"
client_secret = "client secret"

upstream_authority = "example.org"
upstream_use_https = true

public_route_patterns = [
    '/news',
    '/version',
]
