[openid]
issuer_url = "https://oauth.example.org"
introspect_url = "https://oauth.example.org/token/introspect"
client_id = "client id"
client_secret = "client secret"

[[server]]
name = "example.org"
listen = "0.0.0.0:9000"
upstream = "localhost:9090"
public_routes = [
    '.*',
]

[server.tls]
cert = "certs/example.org/cert.pem"
key = "certs/example.org/key.pem"

[[server]]
name = "api.example.org:9000"
listen = "0.0.0.0:9000"
upstream = "localhost:9091"
public_routes = [
    '/version',
]

[server.tls]
cert = "certs/api.example.org/cert.pem"
key = "certs/api.example.org/key.pem"
