listen_addr = "0.0.0.0:9000"

[openid]
issuer_url = "https://oauth.example.org"
introspect_url = "https://oauth.example.org/token/introspect"
client_id = "client id"
client_secret = "client secret"

[[server]]
host = "example.org:9000"
upstream = "localhost:9090"
public_routes = [
    '.*',
]

[[server]]
host = "api.example.org:9000"
upstream = "localhost:9091"
public_routes = [
    '/version',
]
